### ISSUE TITLE
Git integration for editing

### ISSUE THREAD

**Issue by firmart** [NicolasPetton/pass#33]
Sorry to reopen an issue for #8. But if I understand well, there is still no git integration while one modify a password by saving it in a pass-view buffer. 
I saw that it was an upstream issue at the time of #8, however, it's not the case anymore and I don't understand why #8 was closed.
I'm pretty new with emacs (just started one week ago), nevertheless, I tried to bring a solution which does its job : 
```elisp
(defun pass-edit() 
  (interactive) 
  (pass--with-closest-entry entry 
      (password-store-edit entry))) 
```
Of course, there are two points remaining to be improved : 
1. If the password remains unchanged, `pass` displays an error message without explanation ; 
2. the key-binding to save the buffer is `C-x #`  (`server-edit`) in this case since an async-shell has been launched (see `password-store-edit`).

Moreover, I suggest making the pass-view a read-only buffer to prevent users to edit without commit.

Hope that I didn't say dumb things and thank you for this marvellous package!

**Comment by liebkne** [comment]
News?

**Comment by doolio** [comment]
@DamienCassou as mentioned [here](https://github.com/NicolasPetton/pass/issues/8#issuecomment-1840298438) this is no longer an issue (in fact the `defun` suggested by @firmart matches the current implementation minus recent changes to suppress the confirmation messages; perhaps that was not the case when this was first raised) and as such can be closed. 

The only potential issue I see is that the secret is visible in the temp file created to perform the edit but that is because `pass.el` passes this action off to `password-store.el` which in turn passes it off to `pass` and I guess that is simply how it works. So users need to be aware of this in case someone is lurking over their shoulder when editing a password-store entry.

**Comment by doolio** [comment]
@DamienCassou do you agree we can close this or are the observations I made worthy of further consideration?

**Comment by DamienCassou** [comment]
I will close this issue. If anyone wants to reopen a more specific issue, that is always possible. Thank you for caring @doolio.
