### ISSUE TITLE
Missing dependency password-store 2.1.0 on melpa-stable

### ISSUE THREAD

**Issue by lhupfeldt** [NicolasPetton/pass#48]
```
Package pass is incompatible.

     Status: Incompatible because it depends on uninstallable packages.
    Archive: melpa-stable
    Version: 2.0
     Commit: 35e3f86e96878520e690513cdbc1b2753b173e72
    Summary: Major mode for password-store.el
   Requires: emacs-25, password-store-2.1.0 (not available), password-store-otp-0.1.5, f-0.17
```

The version of password-store available on melpa-stable is 1.7.3

**Comment by doolio** [comment]
cc: @DamienCassou the version now on MELPA stable is [1.7.4](https://stable.melpa.org/#/password-store). It seems the version number corresponds to the `password-store` tag version (v1.7.4) rather than the `password-store.el` version (currently v2.1.4 on MELPA Stable) which is maintained in the `password-store` repository. 

I believe the `Package Requires` was changed from 0.1 to 2.1.0 in commit 10a3f89c4ada3aac236073116dd35132cf3ab314.

The [MELPA receipe ](https://github.com/melpa/melpa/blob/master/recipes/password-store) suggests only the *.el files should be fetched but I can confirm with `straight.el` at least that the entire `password-store` repo is in fact fetched. Though it fetches from MELPA and not MELPA Stable. Maybe one for @purcell?

I guess the simplest solution might be set the `Package Requires` to match the version in MELPA Stable or do we need it to match the `password-store` version when the `password-store.el` version was 2.1.0?

**Comment by purcell** [comment]
MELPA Stable versions always come from tags, so this would be the expected behaviour. And yes, the whole repo is fetched, (of course) but not all the files are placed in the resulting package. (No idea what `straight` does.) The elisp repo could either be split out and tagged independently, or the containing repository could have a second set of tags like `elisp-v2.1.0` — the MELPA recipe can specify a pattern for the relevant tags.

**Comment by doolio** [comment]
Thanks Steve. 

> And yes, the whole repo is fetched, (of course) but not all the files are placed in the resulting package. (No idea what straight does.) 

Yes, this is what `straight` does.

> The elisp repo could either be split out and tagged independently, or the containing repository could have a second set of tags like elisp-v2.1.0 — the MELPA recipe can specify a pattern for the relevant tags.

What do you think @calancha is the best approach here?

**Comment by doolio** [comment]
@DamienCassou if you think it is sufficient I can submit a PR to set the Package Requires to 1.7.4 so at least we could consider this issue closed from the perspective of `pass.el` as the situation stands now. Ideally, it would best if @calancha can consider adding an elisp tag as suggested above.

**Comment by DamienCassou** [comment]
A PR would be appreciated, thank you @doolio.

**Comment by doolio** [comment]
> Additionally, please feel free to submit a patch upstream incorporating the new 'elisp' tag.

@calancha Happy too. I added a relevant elisp tag to all pertinent commits (unnecessary?). In doing so I did note the version bump was sometimes noted in the CHANGELOG but not the `.el` file. Can such version bumps really be considered? For other the version bump was made in the `.el` file but not in the CHANGELOG. 

In any case,  I'm not sure how to create a patch that would include such tags. Any idea?

**Comment by calancha** [comment]
> > Additionally, please feel free to submit a patch upstream incorporating the new 'elisp' tag.
> 
> @calancha Happy too. I added a relevant elisp tag to all pertinent commits (unnecessary?). In doing so I did note the version bump was sometimes noted in the CHANGELOG but not the `.el` file. Can such version bumps really be considered? For other the version bump was made in the `.el` file but not in the CHANGELOG.
> 
> In any case, I'm not sure how to create a patch that would include such tags. Any idea?

@doolio I would prioritize changes that have a corresponding entry in the Changelog matching the .el Version header. While we might overlook some versions, it's a reasonable compromise.
Let's continue the discussion on the password-store list. Thank you!
